### PR TITLE
[Needs Testing]

### PR DESCRIPTION
**Pull request by NekoTony**
A possible checks that gets the owner id from appinfo! I'm too tired to test it and i got school.

### CODE REVIEW

**Comment by Nerdietony** [comment]
does it work

**Comment by HexadecimalPython** [comment]
To be tested, haven't had time yet.

**Comment by HexadecimalPython** [comment]
Failed testing stage; No modules could be loaded after the change.
Reason: Unknown
No Sentry errors logged.
PR left open to accommodate proper changes.

**Comment by Nerdietony** [comment]
Ok, opinions on check being a required module?

**Comment by HexadecimalPython** [comment]
Having it as a module instead of utils?
I won't see how that would work/fix the issue.

**Comment by Nerdietony** [comment]
Making it a required import, we can import it then do get_cog() to get the cog and get the function for it. We could also use this to make a command to store other users id's which could support multiple owners.

**Comment by Nerdietony** [comment]
I'll make a pr later.

**Comment by HexadecimalPython** [comment]
that would make it uselessly complicated tho, alternatively we could resort to [Liara](https://github.com/Thessia/Liara)'s way of fetching application owner ID.
Please note that Xeili was heavily influenced by Liara so it should not be an issue.

**Comment by Nerdietony** [comment]
What was Liara method? The code shouldn't be hard to make

**Comment by HexadecimalPython** [comment]
Need to see from the Liara's code, shouldn't be hard to replicate.

**Pull request closed without merging**
