### PR TITLE
Cleaning up various things

### PR DESCRIPTION
**Pull request by SapphicCode**
There'll be a V2 of this PR once I finish throwing up.

### CODE REVIEW

**Comment by sr229** [comment]
What happened to jenkins?

**Comment by Pandentia** [comment]
It's sleeping right now.

**Comment by sr229** [comment]
oh.

**Comment by HexadecimalPython** [comment]
Waiting for confirmation from @Ovyerus since he made the cmd_handler

**Comment by sr229** [comment]
@HexadecimalPython  CC'ed @Ovyerus for Code Review.

**Comment by HexadecimalPython** [comment]
@sr229 Ovy worked on Dusk, not me, he's the one who needs to review it.

**Review by H3xadecimal — APPROVED** [review]
Looks good to me.

**Comment by HexadecimalPython** [comment]
Since this is nothing major and seems to be good

**Pull request merged**
